### ISSUE TITLE
Feature request: add the "active" Switch and the "calibration" switches to objects

### ISSUE THREAD

**Issue by adnet-solutions** [Buzze11/ioBroker.atlas-scientific-ezo-i2c#10]
First of all big thx for that adapter. i really like it.

I would like to have a way inside the objects to see and to switch the active switch for the probes (in my case PH).
i also would like to have a way to trigger the calibration using objects. (prio 2)

The main goal of that is that i like to have the "active" Switch and maybe the calibration as switch inside my VIS.
i use it for my pool and i would like to have a easy way inside the vis to disable the probes in wintertime.
Right now i need to do it in normal iobroker instance setting, which i cant do in my VIS. (or i dont know how)

**Comment by Buzze11** [comment]
Nice to hear that you're happy with my implementation. If you like it I'll be happy about any incoming donation as it's quite time consuming. I'll have a look about your request and hope to get some time beside family and job ;) 
BR Buzze11

**Comment by adnet-solutions** [comment]
How much donation you need to implement that? :-) that feature would helpful more acurate only if a measure needed and not all time as i then can easily trigger a manual measurement if really needed

**Comment by Buzze11** [comment]
A donation is always free to be choosen by anyone who gives a donation. I meant in general it's time consuming, not only related to the the implementation which is requested. But I have spent quite a while with the implementation instead of having free time or family time so by the end its always nice to get something back.. ;)

**Comment by Buzze11** [comment]
Hi bicmac, 

**I have added the first request.** But I changed the request a bit:
There is a new state object per sensor called "IsPaused". It is a boolean switch. This can be set during runtime object based independent from if the sensor is Active" in the configuration. See Readme.md
**Remark: The Active Flag is required as the sensor would not start otherwise and then due to that would not listen to state changes. Due to that reason I introduced the new state to fullfill your requirement.**

Try it out.
BR Buzze11

**Comment by adnet-solutions** [comment]
thx i will try out later. Will be a new release for that or how can i get the version wich include your change?

**Comment by Buzze11** [comment]
You can install from GitHub Source within the Expert Mode of Admin UI. Or you just wait some days until I`ll trigger the next release ;)

**Comment by Buzze11** [comment]
Implemented in new Release v2.0.0 and just published some minutes ago. Have fun with the implementation
